onlyBuiltDependencies:
  - unrs-resolver

overrides:
  cross-spawn@<6.0.6: '>=6.0.6'
  form-data@<2.5.4: '>=2.5.4'
  mem@<4.0.0: '>=4.0.0'
  tough-cookie@<4.1.3: '>=4.1.3'
  unzip-stream@<0.3.2: '>=0.3.2'
  yargs-parser@>=6.0.0 <13.1.2: '>=13.1.2'
