#!/usr/bin/env node
"use strict";

export enum PrefEngineStage {BIDDING, EXCHANGE, CONTRACT, DECIDING, KONTRA, PLAYING, END}

export enum PrefEngineBid {
	NO_BID = -1, BID_PASS = 0,
	BID_SPADE = 1, BID_DIAMOND = 2, BID_DIAMOND_MINE = 3, BID_HEART = 4, BID_HEART_MINE = 5, BID_CLUB = 6, BID_CLUB_MINE = 7,
	BID_BETL = 8, BID_BETL_MINE = 9, BID_SANS = 10, BID_SANS_MINE = 11, BID_PREFERANS = 12, BID_PREFERANS_MINE = 13,

	BID_GAME = 14, BID_YOURS_IS_BETTER = 15,
	BID_GAME_SPADE = 16, BID_GAME_DIAMOND = 17, BID_GAME_HEART = 18, BID_GAME_CLUB = 19,
	BID_GAME_BETL = 20, BID_GAME_SANS = 21, BID_GAME_PREFERANS = 22
}

export enum PrefEngineContract {
	NO_CONTRACT = -1,

	CONTRACT_SPADE = PrefEngineBid.BID_SPADE,
	CONTRACT_DIAMOND = PrefEngineBid.BID_DIAMOND,
	CONTRACT_HEART = PrefEngineBid.BID_HEART,
	CONTRACT_CLUB = PrefEngineBid.BID_CLUB,
	CONTRACT_BETL = PrefEngineBid.BID_BETL,
	CONTRACT_SANS = PrefEngineBid.BID_SANS,
	CONTRACT_PREFERANS = PrefEngineBid.BID_PREFERANS,

	CONTRACT_GAME_SPADE = PrefEngineBid.BID_GAME_SPADE,
	CONTRACT_GAME_DIAMOND = PrefEngineBid.BID_GAME_DIAMOND,
	CONTRACT_GAME_HEART = PrefEngineBid.BID_GAME_HEART,
	CONTRACT_GAME_CLUB = PrefEngineBid.BID_GAME_CLUB,

	CONTRACT_GAME_BETL = PrefEngineBid.BID_GAME_BETL,
	CONTRACT_GAME_SANS = PrefEngineBid.BID_GAME_SANS,
	CONTRACT_GAME_PREFERANS = PrefEngineBid.BID_GAME_PREFERANS
}
